version: '3'
services:
  app:
    image: omardoma/whatsapp-notifications-app:v1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - webnet
    depends_on: 
      - redis

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "/Users/omardoma/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet

networks:
  webnet: